Feature/add tenants for get companies on prem
Bertverbeek4PS/bc2adls_EnvironmentHub pull request #3
Opened 2024-11-18 09:04 UTC by JWK

Enhanced the GetAllCompaniesOfEnvironment procedure to differentiate between SaaS and on-premises environments.
Updated the base URL construction for on-premises environments to include the tenant name as a query parameter.
Ensured that the HTTP request method remains consistent for both environment types.

2024-11-18 15:04 UTC, Bertverbeek4PS commented
@JWK thanks for your PR.
Could you also change the tooltip on page 50102 "ENVHUB Setup"
Specifies the redirect base URL api of the application that will be used to the Business Central integration. Like https://nav.contoso.com:7048/bc/api/v2.0/v1.0/companies.

to

Specifies the redirect base URL api of the application that will be used to the Business Central integration. Like https://nav.contoso.com:7048/bc

2024-11-18 15:44 UTC, JWK commented
> @JWK thanks for your PR. Could you also change the tooltip on page 50102 "ENVHUB Setup" Specifies the redirect base URL api of the application that will be used to the Business Central integration. Like https://nav.contoso.com:7048/bc/api/v2.0/v1.0/companies.
> 
> to
> 
> Specifies the redirect base URL api of the application that will be used to the Business Central integration. Like https://nav.contoso.com:7048/bc

I’ve updated the tooltip.

2024-11-20 12:08 UTC, Bertverbeek4PS requested changes

2024-11-20 12:08 UTC, Bertverbeek4PS commented on src/Communication.Codeunit.al
> +            exit(ENVHUBHttp.RequestMessage(StrSubstNo(onPremUrlLbl, ENVHUBSetup."Base URL", environmentName), Method::Get, '')); //Change of baseUrl with tenant/environment name
Please remove the comment

2024-11-20 12:08 UTC, Bertverbeek4PS commented on src/Communication.Codeunit.al
> +            exit(ENVHUBHttp.RequestMessage(StrSubstNo(onPremUrlLbl, ENVHUBSetup."Base URL", environmentName), Method::Get, '')); //Change of baseUrl with tenant/environment name
@JWK I meant the comment on line 55.
In the labels there must always be a comment.

2024-11-20 12:08 UTC, Bertverbeek4PS commented on src/Communication.Codeunit.al
> +        saasUrlLbl: Label 'https://api.businesscentral.dynamics.com/v2.0/%1/%2/api/v1.0/companies';
Please add the comment here again

2024-11-20 12:08 UTC, Bertverbeek4PS commented on src/Communication.Codeunit.al
> +        onPremUrlLbl: Label '%1/api/v1.0/companies?tenant=%2';
Please add the comment here again

2024-11-20 14:16 UTC, JWK commented on src/Communication.Codeunit.al
> +        saasUrlLbl: Label 'https://api.businesscentral.dynamics.com/v2.0/%1/%2/api/v1.0/companies';
Added the following comment for SaasUrlLbl  '%1 = Tenant ID, %2 = Environment name';

2024-11-20 14:17 UTC, JWK commented on src/Communication.Codeunit.al
> +        onPremUrlLbl: Label '%1/api/v1.0/companies?tenant=%2';
Added the following comment for OnPremUrlLbl '%1 = Base URL, %2 = Environment name';

2024-11-20 14:18 UTC, JWK commented on src/Communication.Codeunit.al
> +            exit(ENVHUBHttp.RequestMessage(StrSubstNo(onPremUrlLbl, ENVHUBSetup."Base URL", environmentName), Method::Get, '')); //Change of baseUrl with tenant/environment name
Removed comment on line 55 and added the label comments.

2024-11-20 14:32 UTC, Bertverbeek4PS approved these changes

2024-11-20 14:32 UTC, merged